graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 4
      label "N"
      graphics [
         x 188
         y 124
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 128
         y 55
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 281
         y 50
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 82
         y 180
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 181
         y 264
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 278
         y 221
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 247
         y 342
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 164
         y 339
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 80
         y 340
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 75
         y 451
      ]
   ]
   node [
      id 14
      label "N"
      graphics [
         x 159
         y 458
      ]
   ]
   node [
      id 17
      label "N"
      graphics [
         x 247
         y 456
      ]
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 17
      label ""
      weight 1.0
   ]
]