graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 97
         y 53
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 198
         y 58
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 311
         y 64
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 407
         y 64
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 98
         y 149
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 203
         y 155
      ]
   ]
   node [
      id 6
      label "A"
      graphics [
         x 313
         y 165
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 410
         y 167
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 102
         y 254
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 209
         y 262
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 313
         y 261
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 414
         y 267
      ]
   ]
   node [
      id 19
      label "N"
      graphics [
         x 102
         y 360
      ]
   ]
   node [
      id 20
      label "N"
      graphics [
         x 214
         y 360
      ]
   ]
   node [
      id 21
      label "N"
      graphics [
         x 327
         y 365
      ]
   ]
   node [
      id 22
      label "N"
      graphics [
         x 419
         y 368
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 19
      target 20
      label ""
      weight 1.0
   ]
   edge [
      source 20
      target 21
      label ""
      weight 1.0
   ]
   edge [
      source 21
      target 22
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 21
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 20
      target 9
      label ""
      weight 1.0
   ]
]